server:
  port: 80

spring:
  application:
    name: cloud-consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: wang936221
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true